---
- name: Keyboard preferences
  osx_defaults:
    state: present
    domain: "{{ mac_defaults.keyboard[item.key].domain }}"
    key: "{{ mac_defaults.keyboard[item.key].key }}"
    type: "{{ mac_defaults.keyboard[item.key].type }}"
    value: "{{ item.value }}"
  with_dict: "{{ mac_settings.keyboard }}"

- name: Animation preferences
  osx_defaults:
    state: present
    domain: "{{ mac_defaults.animations[item.key].domain }}"
    key: "{{ mac_defaults.animations[item.key].key }}"
    type: "{{ mac_defaults.animations[item.key].type }}"
    value: "{{ item.value }}"
  with_dict: "{{ mac_settings.animations }}"
